[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
restartPolicyType = "never"

[[services]]
name = "fastapi-backend"
source = "backend/"
port = 8000

[[services]]  
name = "chainlit-chat"
source = "."
port = 8001