services:
  - type: web
    name: fitfinder-backend
    env: python
    buildCommand: pip install poetry && poetry install --no-interaction --no-ansi
    startCommand: python -m backend.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 8000
    autoDeploy: true
